/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HS22_3SE1;

public class Library {
	public static void main(String[] args) {
		System.out.println("Foo");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
